/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.records;


import com.klichota.jooqdemo.boundary.perstitence.tables.LoanExtension;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanExtensionRecord extends UpdatableRecordImpl<LoanExtensionRecord> implements Record4<Long, Date, Timestamp, Long> {

    private static final long serialVersionUID = 1836224243;

    /**
     * Setter for <code>public.loan_extension.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.loan_extension.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.loan_extension.extended_to</code>.
     */
    public void setExtendedTo(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.loan_extension.extended_to</code>.
     */
    public Date getExtendedTo() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.loan_extension.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.loan_extension.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.loan_extension.loan_id</code>.
     */
    public void setLoanId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.loan_extension.loan_id</code>.
     */
    public Long getLoanId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Date, Timestamp, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Date, Timestamp, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LoanExtension.LOAN_EXTENSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return LoanExtension.LOAN_EXTENSION.EXTENDED_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LoanExtension.LOAN_EXTENSION.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return LoanExtension.LOAN_EXTENSION.LOAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getExtendedTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getExtendedTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanExtensionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanExtensionRecord value2(Date value) {
        setExtendedTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanExtensionRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanExtensionRecord value4(Long value) {
        setLoanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanExtensionRecord values(Long value1, Date value2, Timestamp value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanExtensionRecord
     */
    public LoanExtensionRecord() {
        super(LoanExtension.LOAN_EXTENSION);
    }

    /**
     * Create a detached, initialised LoanExtensionRecord
     */
    public LoanExtensionRecord(Long id, Date extendedTo, Timestamp createdAt, Long loanId) {
        super(LoanExtension.LOAN_EXTENSION);

        set(0, id);
        set(1, extendedTo);
        set(2, createdAt);
        set(3, loanId);
    }
}
