/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.records;


import com.klichota.jooqdemo.boundary.perstitence.tables.Loan;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanRecord extends UpdatableRecordImpl<LoanRecord> implements Record8<Long, String, Timestamp, Date, Date, BigDecimal, BigDecimal, Long> {

    private static final long serialVersionUID = -2075842131;

    /**
     * Setter for <code>public.loan.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.loan.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.loan.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.loan.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.loan.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.loan.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.loan.date_from</code>.
     */
    public void setDateFrom(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.loan.date_from</code>.
     */
    public Date getDateFrom() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>public.loan.date_to</code>.
     */
    public void setDateTo(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.loan.date_to</code>.
     */
    public Date getDateTo() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>public.loan.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.loan.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.loan.cost</code>.
     */
    public void setCost(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.loan.cost</code>.
     */
    public BigDecimal getCost() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.loan.proposal_id</code>.
     */
    public void setProposalId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.loan.proposal_id</code>.
     */
    public Long getProposalId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Timestamp, Date, Date, BigDecimal, BigDecimal, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Timestamp, Date, Date, BigDecimal, BigDecimal, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Loan.LOAN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Loan.LOAN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Loan.LOAN.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Loan.LOAN.DATE_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Loan.LOAN.DATE_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return Loan.LOAN.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return Loan.LOAN.COST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Loan.LOAN.PROPOSAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getDateTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getProposalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getDateTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getProposalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value2(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value4(Date value) {
        setDateFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value5(Date value) {
        setDateTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value6(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value7(BigDecimal value) {
        setCost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord value8(Long value) {
        setProposalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanRecord values(Long value1, String value2, Timestamp value3, Date value4, Date value5, BigDecimal value6, BigDecimal value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanRecord
     */
    public LoanRecord() {
        super(Loan.LOAN);
    }

    /**
     * Create a detached, initialised LoanRecord
     */
    public LoanRecord(Long id, String status, Timestamp createdAt, Date dateFrom, Date dateTo, BigDecimal amount, BigDecimal cost, Long proposalId) {
        super(Loan.LOAN);

        set(0, id);
        set(1, status);
        set(2, createdAt);
        set(3, dateFrom);
        set(4, dateTo);
        set(5, amount);
        set(6, cost);
        set(7, proposalId);
    }
}
