/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.daos;


import com.klichota.jooqdemo.boundary.perstitence.tables.LoanExtension;
import com.klichota.jooqdemo.boundary.perstitence.tables.records.LoanExtensionRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanExtensionDao extends DAOImpl<LoanExtensionRecord, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension, Long> {

    /**
     * Create a new LoanExtensionDao without any configuration
     */
    public LoanExtensionDao() {
        super(LoanExtension.LOAN_EXTENSION, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension.class);
    }

    /**
     * Create a new LoanExtensionDao with an attached configuration
     */
    public LoanExtensionDao(Configuration configuration) {
        super(LoanExtension.LOAN_EXTENSION, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension> fetchById(Long... values) {
        return fetch(LoanExtension.LOAN_EXTENSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension fetchOneById(Long value) {
        return fetchOne(LoanExtension.LOAN_EXTENSION.ID, value);
    }

    /**
     * Fetch records that have <code>extended_to IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension> fetchByExtendedTo(Date... values) {
        return fetch(LoanExtension.LOAN_EXTENSION.EXTENDED_TO, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension> fetchByCreatedAt(Timestamp... values) {
        return fetch(LoanExtension.LOAN_EXTENSION.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>loan_id IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.LoanExtension> fetchByLoanId(Long... values) {
        return fetch(LoanExtension.LOAN_EXTENSION.LOAN_ID, values);
    }
}
