/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.daos;


import com.klichota.jooqdemo.boundary.perstitence.tables.Loan;
import com.klichota.jooqdemo.boundary.perstitence.tables.records.LoanRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanDao extends DAOImpl<LoanRecord, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan, Long> {

    /**
     * Create a new LoanDao without any configuration
     */
    public LoanDao() {
        super(Loan.LOAN, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan.class);
    }

    /**
     * Create a new LoanDao with an attached configuration
     */
    public LoanDao(Configuration configuration) {
        super(Loan.LOAN, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchById(Long... values) {
        return fetch(Loan.LOAN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan fetchOneById(Long value) {
        return fetchOne(Loan.LOAN.ID, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchByStatus(String... values) {
        return fetch(Loan.LOAN.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchByCreatedAt(Timestamp... values) {
        return fetch(Loan.LOAN.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>date_from IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchByDateFrom(Date... values) {
        return fetch(Loan.LOAN.DATE_FROM, values);
    }

    /**
     * Fetch records that have <code>date_to IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchByDateTo(Date... values) {
        return fetch(Loan.LOAN.DATE_TO, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchByAmount(BigDecimal... values) {
        return fetch(Loan.LOAN.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>cost IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchByCost(BigDecimal... values) {
        return fetch(Loan.LOAN.COST, values);
    }

    /**
     * Fetch records that have <code>proposal_id IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Loan> fetchByProposalId(Long... values) {
        return fetch(Loan.LOAN.PROPOSAL_ID, values);
    }
}
