/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.daos;


import com.klichota.jooqdemo.boundary.perstitence.tables.Parameter;
import com.klichota.jooqdemo.boundary.perstitence.tables.records.ParameterRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParameterDao extends DAOImpl<ParameterRecord, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter, Long> {

    /**
     * Create a new ParameterDao without any configuration
     */
    public ParameterDao() {
        super(Parameter.PARAMETER, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter.class);
    }

    /**
     * Create a new ParameterDao with an attached configuration
     */
    public ParameterDao(Configuration configuration) {
        super(Parameter.PARAMETER, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter> fetchById(Long... values) {
        return fetch(Parameter.PARAMETER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter fetchOneById(Long value) {
        return fetchOne(Parameter.PARAMETER.ID, value);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter> fetchByCode(String... values) {
        return fetch(Parameter.PARAMETER.CODE, values);
    }

    /**
     * Fetch records that have <code>int_value IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter> fetchByIntValue(Long... values) {
        return fetch(Parameter.PARAMETER.INT_VALUE, values);
    }

    /**
     * Fetch records that have <code>decimal_value IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Parameter> fetchByDecimalValue(BigDecimal... values) {
        return fetch(Parameter.PARAMETER.DECIMAL_VALUE, values);
    }
}
