/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.daos;


import com.klichota.jooqdemo.boundary.perstitence.tables.Proposal;
import com.klichota.jooqdemo.boundary.perstitence.tables.records.ProposalRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProposalDao extends DAOImpl<ProposalRecord, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal, Long> {

    /**
     * Create a new ProposalDao without any configuration
     */
    public ProposalDao() {
        super(Proposal.PROPOSAL, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal.class);
    }

    /**
     * Create a new ProposalDao with an attached configuration
     */
    public ProposalDao(Configuration configuration) {
        super(Proposal.PROPOSAL, com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal> fetchById(Long... values) {
        return fetch(Proposal.PROPOSAL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal fetchOneById(Long value) {
        return fetchOne(Proposal.PROPOSAL.ID, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal> fetchByStatus(String... values) {
        return fetch(Proposal.PROPOSAL.STATUS, values);
    }

    /**
     * Fetch records that have <code>term IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal> fetchByTerm(Long... values) {
        return fetch(Proposal.PROPOSAL.TERM, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal> fetchByAmount(BigDecimal... values) {
        return fetch(Proposal.PROPOSAL.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.klichota.jooqdemo.boundary.perstitence.tables.pojos.Proposal> fetchByCreatedAt(Timestamp... values) {
        return fetch(Proposal.PROPOSAL.CREATED_AT, values);
    }
}
