/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.loan_extension_seq</code>
     */
    public static final Sequence<Long> LOAN_EXTENSION_SEQ = new SequenceImpl<Long>("loan_extension_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.loan_seq</code>
     */
    public static final Sequence<Long> LOAN_SEQ = new SequenceImpl<Long>("loan_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.parameter_seq</code>
     */
    public static final Sequence<Long> PARAMETER_SEQ = new SequenceImpl<Long>("parameter_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.proposal_seq</code>
     */
    public static final Sequence<Long> PROPOSAL_SEQ = new SequenceImpl<Long>("proposal_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
