/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence;


import com.klichota.jooqdemo.boundary.perstitence.tables.Databasechangelog;
import com.klichota.jooqdemo.boundary.perstitence.tables.Databasechangeloglock;
import com.klichota.jooqdemo.boundary.perstitence.tables.Loan;
import com.klichota.jooqdemo.boundary.perstitence.tables.LoanExtension;
import com.klichota.jooqdemo.boundary.perstitence.tables.Parameter;
import com.klichota.jooqdemo.boundary.perstitence.tables.Proposal;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = com.klichota.jooqdemo.boundary.perstitence.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = com.klichota.jooqdemo.boundary.perstitence.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.loan</code>.
     */
    public static final Loan LOAN = com.klichota.jooqdemo.boundary.perstitence.tables.Loan.LOAN;

    /**
     * The table <code>public.loan_extension</code>.
     */
    public static final LoanExtension LOAN_EXTENSION = com.klichota.jooqdemo.boundary.perstitence.tables.LoanExtension.LOAN_EXTENSION;

    /**
     * The table <code>public.parameter</code>.
     */
    public static final Parameter PARAMETER = com.klichota.jooqdemo.boundary.perstitence.tables.Parameter.PARAMETER;

    /**
     * The table <code>public.proposal</code>.
     */
    public static final Proposal PROPOSAL = com.klichota.jooqdemo.boundary.perstitence.tables.Proposal.PROPOSAL;
}
