/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Loan implements Serializable {

    private static final long serialVersionUID = -958278360;

    private Long       id;
    private String     status;
    private Timestamp  createdAt;
    private Date       dateFrom;
    private Date       dateTo;
    private BigDecimal amount;
    private BigDecimal cost;
    private Long       proposalId;

    public Loan() {}

    public Loan(Loan value) {
        this.id = value.id;
        this.status = value.status;
        this.createdAt = value.createdAt;
        this.dateFrom = value.dateFrom;
        this.dateTo = value.dateTo;
        this.amount = value.amount;
        this.cost = value.cost;
        this.proposalId = value.proposalId;
    }

    public Loan(
        Long       id,
        String     status,
        Timestamp  createdAt,
        Date       dateFrom,
        Date       dateTo,
        BigDecimal amount,
        BigDecimal cost,
        Long       proposalId
    ) {
        this.id = id;
        this.status = status;
        this.createdAt = createdAt;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.amount = amount;
        this.cost = cost;
        this.proposalId = proposalId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Date getDateFrom() {
        return this.dateFrom;
    }

    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public Date getDateTo() {
        return this.dateTo;
    }

    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getCost() {
        return this.cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public Long getProposalId() {
        return this.proposalId;
    }

    public void setProposalId(Long proposalId) {
        this.proposalId = proposalId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Loan (");

        sb.append(id);
        sb.append(", ").append(status);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(dateFrom);
        sb.append(", ").append(dateTo);
        sb.append(", ").append(amount);
        sb.append(", ").append(cost);
        sb.append(", ").append(proposalId);

        sb.append(")");
        return sb.toString();
    }
}
