/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanExtension implements Serializable {

    private static final long serialVersionUID = 1277093575;

    private Long      id;
    private Date      extendedTo;
    private Timestamp createdAt;
    private Long      loanId;

    public LoanExtension() {}

    public LoanExtension(LoanExtension value) {
        this.id = value.id;
        this.extendedTo = value.extendedTo;
        this.createdAt = value.createdAt;
        this.loanId = value.loanId;
    }

    public LoanExtension(
        Long      id,
        Date      extendedTo,
        Timestamp createdAt,
        Long      loanId
    ) {
        this.id = id;
        this.extendedTo = extendedTo;
        this.createdAt = createdAt;
        this.loanId = loanId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getExtendedTo() {
        return this.extendedTo;
    }

    public void setExtendedTo(Date extendedTo) {
        this.extendedTo = extendedTo;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Long getLoanId() {
        return this.loanId;
    }

    public void setLoanId(Long loanId) {
        this.loanId = loanId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LoanExtension (");

        sb.append(id);
        sb.append(", ").append(extendedTo);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(loanId);

        sb.append(")");
        return sb.toString();
    }
}
