/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parameter implements Serializable {

    private static final long serialVersionUID = -660751675;

    private Long       id;
    private String     code;
    private Long       intValue;
    private BigDecimal decimalValue;

    public Parameter() {}

    public Parameter(Parameter value) {
        this.id = value.id;
        this.code = value.code;
        this.intValue = value.intValue;
        this.decimalValue = value.decimalValue;
    }

    public Parameter(
        Long       id,
        String     code,
        Long       intValue,
        BigDecimal decimalValue
    ) {
        this.id = id;
        this.code = code;
        this.intValue = intValue;
        this.decimalValue = decimalValue;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Long getIntValue() {
        return this.intValue;
    }

    public void setIntValue(Long intValue) {
        this.intValue = intValue;
    }

    public BigDecimal getDecimalValue() {
        return this.decimalValue;
    }

    public void setDecimalValue(BigDecimal decimalValue) {
        this.decimalValue = decimalValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Parameter (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(intValue);
        sb.append(", ").append(decimalValue);

        sb.append(")");
        return sb.toString();
    }
}
