/*
 * This file is generated by jOOQ.
 */
package com.klichota.jooqdemo.boundary.perstitence.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Proposal implements Serializable {

    private static final long serialVersionUID = 1805481367;

    private Long       id;
    private String     status;
    private Long       term;
    private BigDecimal amount;
    private Timestamp  createdAt;

    public Proposal() {}

    public Proposal(Proposal value) {
        this.id = value.id;
        this.status = value.status;
        this.term = value.term;
        this.amount = value.amount;
        this.createdAt = value.createdAt;
    }

    public Proposal(
        Long       id,
        String     status,
        Long       term,
        BigDecimal amount,
        Timestamp  createdAt
    ) {
        this.id = id;
        this.status = status;
        this.term = term;
        this.amount = amount;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getTerm() {
        return this.term;
    }

    public void setTerm(Long term) {
        this.term = term;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Proposal (");

        sb.append(id);
        sb.append(", ").append(status);
        sb.append(", ").append(term);
        sb.append(", ").append(amount);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
